baseURL = 'https://lingual.dev/'
languageCode = 'en-us'
title = 'Lingual'
theme = "lingual"
capitalizeListTitles = false

[module]
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
[[module.mounts]]
source = 'node_modules'
target = 'assets'
[[module.mounts]]
source = 'assets'
target = 'assets'

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.highlight]
style = "nord"
[markup.goldmark.extensions.typographer]
enDash = "--"

[minify]
disableHTML = true

